
# Legendary Tooltips Configuration Instructions
#
# *** READ THIS FIRST ***
#
# By default, this mod does not apply special borders to most items.  It was designed to work well with mod packs
# where the available selection of items can vary widely, so it is up to the user or mod pack designer to customize as needed.
# There are many options available for setting up which custom borders (also called frames) apply to which items.  Follow these steps:
#   1. Decide which items you want to have custom borders, and which borders.  Note that each custom border has a number associated with it (starting at 0).
#   2. For each custom border you want to use, fill out the associated list in the "definitions" section.  This will be filled out with a list of "selectors",
#      each of which tell the mod what items have that border.  Please read the information above the definitions section for specifics.
#   3. Selectors for borders are checked in the order provided in the "priorities" section.  Once a match is found, that border is displayed.
#      For example, if border 0 had the selector "%Diamond" and border 1 had the selector "diamond_sword", they would both match for diamond swords.
#      In this case, whichever border number came first in the priority list would be the border that would get drawn in-game.
#   4. Optionally, border colors associated with custom borders can be set in the "colors" section.  The start color is the color at the top of the tooltip,
#      and the end color is the bottom, with a smooth transition between.  Please read the information above the color section for specifics.
[client]

	[client.visual_options]
		# Whether item names in tooltips should have a line under them separating them from the rest of the tooltip.
		name_separator = true
		# If enabled, tooltip border colors will match item rarity colors (except for custom borders).
		borders_match_rarity = true
		# If enabled, tooltips will display a drop shadow.
		tooltip_shadow = true
		# If enabled, items showing a custom border will have a special shine effect when hovered over.
		shine_effect = true
		# If enabled, tooltip titles will be drawn centered.
		centered_title = true
		# If enabled, tooltips with custom borders will always be at least wide enough to display all border decorations.
		enforce_minimum_width = false

	# Entry types:
	#    Item name - Use item name for vanilla items or include mod name for modded items.  Examples: "minecraft:stick", "iron_ore"
	#    Tag - $ followed by tag name.  Examples: "$forge:stone", "$planks"
	#    Mod name - @ followed by mod identifier.  Examples: "@spoiledeggs"
	#    Rarity - ! followed by item's rarity.  This is ONLY vanilla rarities.  Examples: "!uncommon", "!rare", "!epic"
	#    Item name color - # followed by color hex code, the hex code must match exactly.  Examples: "#23F632"
	#    Display name - % followed by any text.  Will match any item with this text in its tooltip display name.  Examples: "%Netherite", "%[Uncommon]"
	#    Tooltip text - Will match any item with this text anywhere in the tooltip text (besides the name).  Examples: "^Legendary"
	#    NBT tag - & followed by tag name and optional comparator (=, >, <, or !=) and value, in the format <tag><comparator><value> or just <tag>.  Examples: "&Damage=0", "&Tier>1", "&map!=128", "&Enchantments"
	[client.definitions]
		level0_entries = ["arcanus:adept_wand"]
		level1_entries = ["betterend:aeternium_helmet", "betterend:aeternium_chestplate", "betterend:aeternium_leggings", "betterend:aeternium_boots", "betterend:aeternium_sword", "betterend:aeternium_pickaxe", "betterend:aeternium_shovel", "betterend:aeternium_axe", "betterend:aeternium_hoe", "betterend:aeternium_hammer", "betterend:elytra_armored"]
		level2_entries = ["additionaladditions:rose_gold_helmet", "additionaladditions:rose_gold_chestplate", "additionaladditions:rose_gold_leggings", "additionaladditions:rose_gold_boots", "additionaladditions:rose_gold_sword", "additionaladditions:rose_gold_pickaxe", "additionaladditions:rose_gold_shovel", "additionaladditions:rose_gold_axe", "additionaladditions:rose_gold_hoe"]
		level3_entries = [""]
		level4_entries = ["arcanus:master_wand", "betterend:crystalite_helmet", "betterend:crystalite_chestplate", "betterend:crystalite_leggings", "betterend:crystalite_boots", "betterend:elytra_crystalite"]
		level5_entries = ["additionaladditions:watering_can", "artifality:floral_staff", "artifality:forest_staff", "artifality:harvest_staff"]
		level6_entries = ["minecraft:netherite_helmet", "minecraft:netherite_chestplate", "minecraft:netherite_leggings", "minecraft:netherite_boots", "minecraft:netherite_sword", "minecraft:netherite_pickaxe", "minecraft:netherite_shovel", "minecraft:netherite_axe", "minecraft:netherite_hoe", "betterend:netherite_hammer", "harvest_scythes:netherite_scythe", "harvest_scythes:netherite_machete", "adventurez:stone_golem_helmet", "adventurez:stone_golem_chestplate", "adventurez:stone_golem_leggings", "adventurez:stone_golem_boots"]
		level7_entries = ["techreborn:advanced_drill", "techreborn:advanced_chainsaw", "techreborn:advanced_jackhammer", "techreborn:omni_tool"]
		level8_entries = ["dragonloot:dragon_helmet", "dragonloot:dragon_chestplate", "dragonloot:dragon_leggings", "dragonloot:dragon_boots", "dragonloot:upgraded_dragon_chestplate", "dragonloot:dragon_sword", "dragonloot:dragon_bow", "dragonloot:dragon_crossbow", "dragonloot:dragon_trident", "dragonloot:dragon_pickaxe", "dragonloot:dragon_shovel", "dragonloot:dragon_axe", "dragonloot:dragon_hoe", "harvest_scythes:dragon_scythe", "harvest_scythes:dragon_machete"]
		level9_entries = ["techreborn:quantum_helmet", "techreborn:quantum_chestplate", "techreborn:quantum_leggings", "techreborn:quantum_boots", "techreborn:quantum_helmet", "techreborn:nanosaber", "techreborn:industrial_drill", "techreborn:industrial_chainsaw", "techreborn:industrial_jackhammer"]
		level10_entries = [""]
		level11_entries = [""]
		level12_entries = [""]
		level13_entries = [""]
		level14_entries = [""]
		level15_entries = [""]

	# Set border priorities here.  This should be a list of numbers that correspond to border levels, with numbers coming first being higher priority.  Optionally, -1 can be inserted to indicate relative priority of data and api-defined borders.  If you don't know what that means, don't worry about it.
	[client.priorities]
		priorities = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

	# The start and end border colors and background colors of each level.
	# Note that they can be entered as any one of: a decimal or hex color code in the format 0xAARRGGBB or 0xRRGGBB, OR a string color name or color code.
	# Examples: 0xFFFF00, 0xFF73D984, 4290445567, "red", "#FFCC00" are all valid.
	[client.colors]
		level0_start_color = 4288244002
		level0_end_color = 4284168989
		level0_bg_color = 4027976192
		level1_start_color = 4285103244
		level1_end_color = 4282010721
		level1_bg_color = 4027976192
		level2_start_color = 4285547837
		level2_end_color = 4283704099
		level2_bg_color = 4027976192
		level3_start_color = 4287701767
		level3_end_color = 4286677893
		level3_bg_color = 4027976192
		level4_start_color = 4278226892
		level4_end_color = 4278471562
		level4_bg_color = 4027976192
		level5_start_color = 4284238893
		level5_end_color = 4284238893
		level5_bg_color = 4027976192
		level6_start_color = 4285553287
		level6_end_color = 4281939286
		level6_bg_color = 4027976192
		level7_start_color = 4286417553
		level7_end_color = 4286417553
		level7_bg_color = 4027976192
		level8_start_color = 4289040822
		level8_end_color = 4289040822
		level8_bg_color = 4027976192
		level9_start_color = 4294965979
		level9_end_color = 4294959021
		level9_bg_color = 4027976192
		level10_start_color = 4288244002
		level10_end_color = 4284103197
		level10_bg_color = 4027976192
		level11_start_color = 4288244002
		level11_end_color = 4284103197
		level11_bg_color = 4027976192
		level12_start_color = 4288244002
		level12_end_color = 4284103197
		level12_bg_color = 4027976192
		level13_start_color = 4288244002
		level13_end_color = 4284103197
		level13_bg_color = 4027976192
		level14_start_color = 4288244002
		level14_end_color = 4284103197
		level14_bg_color = 4027976192
		level15_start_color = 4288244002
		level15_end_color = 4284103197
		level15_bg_color = 4027976192

